# Generated by Django 5.0 on 2024-05-03 18:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='image/')),
                ('secretkey', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtes', models.IntegerField()),
                ('secretkey', models.UUIDField(default=uuid.uuid4)),
                ('Produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='app_stock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu', models.IntegerField(editable=False)),
                ('qtev', models.IntegerField()),
                ('pttc', models.IntegerField(default=0, editable=False)),
                ('datev', models.DateField()),
                ('secretkey', models.UUIDField(default=uuid.uuid4)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qteachat', to='app_stock.produit')),
            ],
        ),
    ]
